/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountDetailsAndActionsIntegration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountDetailsAndActionsIntegrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountDetailsAndActionsIntegration
        //private AccountDetailsAndActionsIntegration instance;

        public AccountDetailsAndActionsIntegrationTests()
        {
            // TODO uncomment below to create an instance of AccountDetailsAndActionsIntegration
            //instance = new AccountDetailsAndActionsIntegration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountDetailsAndActionsIntegration
        /// </summary>
        [Fact]
        public void AccountDetailsAndActionsIntegrationInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountDetailsAndActionsIntegration
            //Assert.IsType<AccountDetailsAndActionsIntegration>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'SquareImage'
        /// </summary>
        [Fact]
        public void SquareImageTest()
        {
            // TODO unit test for the property 'SquareImage'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'PassthroughAvailable'
        /// </summary>
        [Fact]
        public void PassthroughAvailableTest()
        {
            // TODO unit test for the property 'PassthroughAvailable'
        }
        /// <summary>
        /// Test the property 'AvailableModelOperations'
        /// </summary>
        [Fact]
        public void AvailableModelOperationsTest()
        {
            // TODO unit test for the property 'AvailableModelOperations'
        }

    }

}
