/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountToken
        //private AccountToken instance;

        public AccountTokenTests()
        {
            // TODO uncomment below to create an instance of AccountToken
            //instance = new AccountToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountToken
        /// </summary>
        [Fact]
        public void AccountTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountToken
            //Assert.IsType<AccountToken>(instance);
        }


        /// <summary>
        /// Test the property '_AccountToken'
        /// </summary>
        [Fact]
        public void _AccountTokenTest()
        {
            // TODO unit test for the property '_AccountToken'
        }
        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Fact]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }

    }

}
