/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing AvailableActions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailableActionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailableActions
        //private AvailableActions instance;

        public AvailableActionsTests()
        {
            // TODO uncomment below to create an instance of AvailableActions
            //instance = new AvailableActions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailableActions
        /// </summary>
        [Fact]
        public void AvailableActionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailableActions
            //Assert.IsType<AvailableActions>(instance);
        }


        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Fact]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }
        /// <summary>
        /// Test the property 'PassthroughAvailable'
        /// </summary>
        [Fact]
        public void PassthroughAvailableTest()
        {
            // TODO unit test for the property 'PassthroughAvailable'
        }
        /// <summary>
        /// Test the property 'AvailableModelOperations'
        /// </summary>
        [Fact]
        public void AvailableModelOperationsTest()
        {
            // TODO unit test for the property 'AvailableModelOperations'
        }

    }

}
