/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing CommonModelScopesBodyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonModelScopesBodyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonModelScopesBodyRequest
        //private CommonModelScopesBodyRequest instance;

        public CommonModelScopesBodyRequestTests()
        {
            // TODO uncomment below to create an instance of CommonModelScopesBodyRequest
            //instance = new CommonModelScopesBodyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonModelScopesBodyRequest
        /// </summary>
        [Fact]
        public void CommonModelScopesBodyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonModelScopesBodyRequest
            //Assert.IsType<CommonModelScopesBodyRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'EnabledActions'
        /// </summary>
        [Fact]
        public void EnabledActionsTest()
        {
            // TODO unit test for the property 'EnabledActions'
        }
        /// <summary>
        /// Test the property 'DisabledFields'
        /// </summary>
        [Fact]
        public void DisabledFieldsTest()
        {
            // TODO unit test for the property 'DisabledFields'
        }

    }

}
