/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing ConditionSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConditionSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConditionSchema
        //private ConditionSchema instance;

        public ConditionSchemaTests()
        {
            // TODO uncomment below to create an instance of ConditionSchema
            //instance = new ConditionSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConditionSchema
        /// </summary>
        [Fact]
        public void ConditionSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConditionSchema
            //Assert.IsType<ConditionSchema>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CommonModel'
        /// </summary>
        [Fact]
        public void CommonModelTest()
        {
            // TODO unit test for the property 'CommonModel'
        }
        /// <summary>
        /// Test the property 'NativeName'
        /// </summary>
        [Fact]
        public void NativeNameTest()
        {
            // TODO unit test for the property 'NativeName'
        }
        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Fact]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'IsUnique'
        /// </summary>
        [Fact]
        public void IsUniqueTest()
        {
            // TODO unit test for the property 'IsUnique'
        }
        /// <summary>
        /// Test the property 'ConditionType'
        /// </summary>
        [Fact]
        public void ConditionTypeTest()
        {
            // TODO unit test for the property 'ConditionType'
        }
        /// <summary>
        /// Test the property 'Operators'
        /// </summary>
        [Fact]
        public void OperatorsTest()
        {
            // TODO unit test for the property 'Operators'
        }

    }

}
