/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing CountryEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CountryEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CountryEnum
        //private CountryEnum instance;

        public CountryEnumTests()
        {
            // TODO uncomment below to create an instance of CountryEnum
            //instance = new CountryEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountryEnum
        /// </summary>
        [Fact]
        public void CountryEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" CountryEnum
            //Assert.IsType<CountryEnum>(instance);
        }



    }

}
