/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing Deduction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeductionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deduction
        //private Deduction instance;

        public DeductionTests()
        {
            // TODO uncomment below to create an instance of Deduction
            //instance = new Deduction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deduction
        /// </summary>
        [Fact]
        public void DeductionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deduction
            //Assert.IsType<Deduction>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'EmployeePayrollRun'
        /// </summary>
        [Fact]
        public void EmployeePayrollRunTest()
        {
            // TODO unit test for the property 'EmployeePayrollRun'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'EmployeeDeduction'
        /// </summary>
        [Fact]
        public void EmployeeDeductionTest()
        {
            // TODO unit test for the property 'EmployeeDeduction'
        }
        /// <summary>
        /// Test the property 'CompanyDeduction'
        /// </summary>
        [Fact]
        public void CompanyDeductionTest()
        {
            // TODO unit test for the property 'CompanyDeduction'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'RemoteWasDeleted'
        /// </summary>
        [Fact]
        public void RemoteWasDeletedTest()
        {
            // TODO unit test for the property 'RemoteWasDeleted'
        }

    }

}
