/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing Earning
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EarningTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Earning
        //private Earning instance;

        public EarningTests()
        {
            // TODO uncomment below to create an instance of Earning
            //instance = new Earning();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Earning
        /// </summary>
        [Fact]
        public void EarningInstanceTest()
        {
            // TODO uncomment below to test "IsType" Earning
            //Assert.IsType<Earning>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'EmployeePayrollRun'
        /// </summary>
        [Fact]
        public void EmployeePayrollRunTest()
        {
            // TODO unit test for the property 'EmployeePayrollRun'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'RemoteWasDeleted'
        /// </summary>
        [Fact]
        public void RemoteWasDeletedTest()
        {
            // TODO unit test for the property 'RemoteWasDeleted'
        }

    }

}
