/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing EmploymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmploymentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmploymentRequest
        //private EmploymentRequest instance;

        public EmploymentRequestTests()
        {
            // TODO uncomment below to create an instance of EmploymentRequest
            //instance = new EmploymentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmploymentRequest
        /// </summary>
        [Fact]
        public void EmploymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmploymentRequest
            //Assert.IsType<EmploymentRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'JobTitle'
        /// </summary>
        [Fact]
        public void JobTitleTest()
        {
            // TODO unit test for the property 'JobTitle'
        }
        /// <summary>
        /// Test the property 'PayRate'
        /// </summary>
        [Fact]
        public void PayRateTest()
        {
            // TODO unit test for the property 'PayRate'
        }
        /// <summary>
        /// Test the property 'PayPeriod'
        /// </summary>
        [Fact]
        public void PayPeriodTest()
        {
            // TODO unit test for the property 'PayPeriod'
        }
        /// <summary>
        /// Test the property 'PayFrequency'
        /// </summary>
        [Fact]
        public void PayFrequencyTest()
        {
            // TODO unit test for the property 'PayFrequency'
        }
        /// <summary>
        /// Test the property 'PayCurrency'
        /// </summary>
        [Fact]
        public void PayCurrencyTest()
        {
            // TODO unit test for the property 'PayCurrency'
        }
        /// <summary>
        /// Test the property 'FlsaStatus'
        /// </summary>
        [Fact]
        public void FlsaStatusTest()
        {
            // TODO unit test for the property 'FlsaStatus'
        }
        /// <summary>
        /// Test the property 'EffectiveDate'
        /// </summary>
        [Fact]
        public void EffectiveDateTest()
        {
            // TODO unit test for the property 'EffectiveDate'
        }
        /// <summary>
        /// Test the property 'EmploymentType'
        /// </summary>
        [Fact]
        public void EmploymentTypeTest()
        {
            // TODO unit test for the property 'EmploymentType'
        }

    }

}
