/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing EndUserDetailsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EndUserDetailsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EndUserDetailsRequest
        //private EndUserDetailsRequest instance;

        public EndUserDetailsRequestTests()
        {
            // TODO uncomment below to create an instance of EndUserDetailsRequest
            //instance = new EndUserDetailsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EndUserDetailsRequest
        /// </summary>
        [Fact]
        public void EndUserDetailsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EndUserDetailsRequest
            //Assert.IsType<EndUserDetailsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'EndUserEmailAddress'
        /// </summary>
        [Fact]
        public void EndUserEmailAddressTest()
        {
            // TODO unit test for the property 'EndUserEmailAddress'
        }
        /// <summary>
        /// Test the property 'EndUserOrganizationName'
        /// </summary>
        [Fact]
        public void EndUserOrganizationNameTest()
        {
            // TODO unit test for the property 'EndUserOrganizationName'
        }
        /// <summary>
        /// Test the property 'EndUserOriginId'
        /// </summary>
        [Fact]
        public void EndUserOriginIdTest()
        {
            // TODO unit test for the property 'EndUserOriginId'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Integration'
        /// </summary>
        [Fact]
        public void IntegrationTest()
        {
            // TODO unit test for the property 'Integration'
        }
        /// <summary>
        /// Test the property 'LinkExpiryMins'
        /// </summary>
        [Fact]
        public void LinkExpiryMinsTest()
        {
            // TODO unit test for the property 'LinkExpiryMins'
        }

    }

}
