/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing EthnicityEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EthnicityEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EthnicityEnum
        //private EthnicityEnum instance;

        public EthnicityEnumTests()
        {
            // TODO uncomment below to create an instance of EthnicityEnum
            //instance = new EthnicityEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EthnicityEnum
        /// </summary>
        [Fact]
        public void EthnicityEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" EthnicityEnum
            //Assert.IsType<EthnicityEnum>(instance);
        }



    }

}
