/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedAccountStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedAccountStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedAccountStatus
        //private LinkedAccountStatus instance;

        public LinkedAccountStatusTests()
        {
            // TODO uncomment below to create an instance of LinkedAccountStatus
            //instance = new LinkedAccountStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedAccountStatus
        /// </summary>
        [Fact]
        public void LinkedAccountStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedAccountStatus
            //Assert.IsType<LinkedAccountStatus>(instance);
        }


        /// <summary>
        /// Test the property '_LinkedAccountStatus'
        /// </summary>
        [Fact]
        public void _LinkedAccountStatusTest()
        {
            // TODO unit test for the property '_LinkedAccountStatus'
        }
        /// <summary>
        /// Test the property 'CanMakeRequest'
        /// </summary>
        [Fact]
        public void CanMakeRequestTest()
        {
            // TODO unit test for the property 'CanMakeRequest'
        }

    }

}
