/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedAccountSelectiveSyncConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedAccountSelectiveSyncConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedAccountSelectiveSyncConfiguration
        //private LinkedAccountSelectiveSyncConfiguration instance;

        public LinkedAccountSelectiveSyncConfigurationTests()
        {
            // TODO uncomment below to create an instance of LinkedAccountSelectiveSyncConfiguration
            //instance = new LinkedAccountSelectiveSyncConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedAccountSelectiveSyncConfiguration
        /// </summary>
        [Fact]
        public void LinkedAccountSelectiveSyncConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedAccountSelectiveSyncConfiguration
            //Assert.IsType<LinkedAccountSelectiveSyncConfiguration>(instance);
        }


        /// <summary>
        /// Test the property 'LinkedAccountConditions'
        /// </summary>
        [Fact]
        public void LinkedAccountConditionsTest()
        {
            // TODO unit test for the property 'LinkedAccountConditions'
        }

    }

}
