/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedAccountSelectiveSyncConfigurationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedAccountSelectiveSyncConfigurationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedAccountSelectiveSyncConfigurationRequest
        //private LinkedAccountSelectiveSyncConfigurationRequest instance;

        public LinkedAccountSelectiveSyncConfigurationRequestTests()
        {
            // TODO uncomment below to create an instance of LinkedAccountSelectiveSyncConfigurationRequest
            //instance = new LinkedAccountSelectiveSyncConfigurationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedAccountSelectiveSyncConfigurationRequest
        /// </summary>
        [Fact]
        public void LinkedAccountSelectiveSyncConfigurationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedAccountSelectiveSyncConfigurationRequest
            //Assert.IsType<LinkedAccountSelectiveSyncConfigurationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'LinkedAccountConditions'
        /// </summary>
        [Fact]
        public void LinkedAccountConditionsTest()
        {
            // TODO unit test for the property 'LinkedAccountConditions'
        }

    }

}
