/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedAccountCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedAccountConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedAccountCondition
        //private LinkedAccountCondition instance;

        public LinkedAccountConditionTests()
        {
            // TODO uncomment below to create an instance of LinkedAccountCondition
            //instance = new LinkedAccountCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedAccountCondition
        /// </summary>
        [Fact]
        public void LinkedAccountConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedAccountCondition
            //Assert.IsType<LinkedAccountCondition>(instance);
        }


        /// <summary>
        /// Test the property 'ConditionSchemaId'
        /// </summary>
        [Fact]
        public void ConditionSchemaIdTest()
        {
            // TODO unit test for the property 'ConditionSchemaId'
        }
        /// <summary>
        /// Test the property 'CommonModel'
        /// </summary>
        [Fact]
        public void CommonModelTest()
        {
            // TODO unit test for the property 'CommonModel'
        }
        /// <summary>
        /// Test the property 'NativeName'
        /// </summary>
        [Fact]
        public void NativeNameTest()
        {
            // TODO unit test for the property 'NativeName'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Fact]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }

    }

}
