/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing MetaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetaResponse
        //private MetaResponse instance;

        public MetaResponseTests()
        {
            // TODO uncomment below to create an instance of MetaResponse
            //instance = new MetaResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetaResponse
        /// </summary>
        [Fact]
        public void MetaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetaResponse
            //Assert.IsType<MetaResponse>(instance);
        }


        /// <summary>
        /// Test the property 'RequestSchema'
        /// </summary>
        [Fact]
        public void RequestSchemaTest()
        {
            // TODO unit test for the property 'RequestSchema'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'HasConditionalParams'
        /// </summary>
        [Fact]
        public void HasConditionalParamsTest()
        {
            // TODO unit test for the property 'HasConditionalParams'
        }
        /// <summary>
        /// Test the property 'HasRequiredLinkedAccountParams'
        /// </summary>
        [Fact]
        public void HasRequiredLinkedAccountParamsTest()
        {
            // TODO unit test for the property 'HasRequiredLinkedAccountParams'
        }

    }

}
