/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing OperatorSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperatorSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperatorSchema
        //private OperatorSchema instance;

        public OperatorSchemaTests()
        {
            // TODO uncomment below to create an instance of OperatorSchema
            //instance = new OperatorSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperatorSchema
        /// </summary>
        [Fact]
        public void OperatorSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperatorSchema
            //Assert.IsType<OperatorSchema>(instance);
        }


        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'IsUnique'
        /// </summary>
        [Fact]
        public void IsUniqueTest()
        {
            // TODO unit test for the property 'IsUnique'
        }

    }

}
