/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedAccountDetailsAndActionsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedAccountDetailsAndActionsListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedAccountDetailsAndActionsList
        //private PaginatedAccountDetailsAndActionsList instance;

        public PaginatedAccountDetailsAndActionsListTests()
        {
            // TODO uncomment below to create an instance of PaginatedAccountDetailsAndActionsList
            //instance = new PaginatedAccountDetailsAndActionsList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedAccountDetailsAndActionsList
        /// </summary>
        [Fact]
        public void PaginatedAccountDetailsAndActionsListInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedAccountDetailsAndActionsList
            //Assert.IsType<PaginatedAccountDetailsAndActionsList>(instance);
        }


        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
