/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.HRISClient.Api;
using Merge.HRISClient.Model;
using Merge.HRISClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.HRISClient.Test.Model
{
    /// <summary>
    ///  Class for testing TimeOffRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeOffRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeOffRequest
        //private TimeOffRequest instance;

        public TimeOffRequestTests()
        {
            // TODO uncomment below to create an instance of TimeOffRequest
            //instance = new TimeOffRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeOffRequest
        /// </summary>
        [Fact]
        public void TimeOffRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeOffRequest
            //Assert.IsType<TimeOffRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'Employee'
        /// </summary>
        [Fact]
        public void EmployeeTest()
        {
            // TODO unit test for the property 'Employee'
        }
        /// <summary>
        /// Test the property 'Approver'
        /// </summary>
        [Fact]
        public void ApproverTest()
        {
            // TODO unit test for the property 'Approver'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'EmployeeNote'
        /// </summary>
        [Fact]
        public void EmployeeNoteTest()
        {
            // TODO unit test for the property 'EmployeeNote'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'RequestType'
        /// </summary>
        [Fact]
        public void RequestTypeTest()
        {
            // TODO unit test for the property 'RequestType'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

    }

}
