/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Merge.HRISClient.Client;
using Merge.HRISClient.Api;
// uncomment below to import models
//using Merge.HRISClient.Model;

namespace Merge.HRISClient.Test.Api
{
    /// <summary>
    ///  Class for testing EmployeePayrollRunsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmployeePayrollRunsApiTests : IDisposable
    {
        private EmployeePayrollRunsApi instance;

        public EmployeePayrollRunsApiTests()
        {
            instance = new EmployeePayrollRunsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeePayrollRunsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmployeePayrollRunsApi
            //Assert.IsType<EmployeePayrollRunsApi>(instance);
        }

        /// <summary>
        /// Test EmployeePayrollRunsList
        /// </summary>
        [Fact]
        public void EmployeePayrollRunsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //DateTime? createdAfter = null;
            //DateTime? createdBefore = null;
            //string cursor = null;
            //string employeeId = null;
            //DateTime? endedAfter = null;
            //DateTime? endedBefore = null;
            //bool? includeDeletedData = null;
            //bool? includeRemoteData = null;
            //DateTime? modifiedAfter = null;
            //DateTime? modifiedBefore = null;
            //int? pageSize = null;
            //string payrollRunId = null;
            //string remoteId = null;
            //DateTime? startedAfter = null;
            //DateTime? startedBefore = null;
            //var response = instance.EmployeePayrollRunsList(xAccountToken, createdAfter, createdBefore, cursor, employeeId, endedAfter, endedBefore, includeDeletedData, includeRemoteData, modifiedAfter, modifiedBefore, pageSize, payrollRunId, remoteId, startedAfter, startedBefore);
            //Assert.IsType<PaginatedEmployeePayrollRunList>(response);
        }

        /// <summary>
        /// Test EmployeePayrollRunsRetrieve
        /// </summary>
        [Fact]
        public void EmployeePayrollRunsRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //bool? includeRemoteData = null;
            //var response = instance.EmployeePayrollRunsRetrieve(xAccountToken, id, includeRemoteData);
            //Assert.IsType<EmployeePayrollRun>(response);
        }
    }
}
