/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Merge.HRISClient.Client;
using Merge.HRISClient.Api;
// uncomment below to import models
//using Merge.HRISClient.Model;

namespace Merge.HRISClient.Test.Api
{
    /// <summary>
    ///  Class for testing LinkTokenApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LinkTokenApiTests : IDisposable
    {
        private LinkTokenApi instance;

        public LinkTokenApiTests()
        {
            instance = new LinkTokenApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkTokenApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LinkTokenApi
            //Assert.IsType<LinkTokenApi>(instance);
        }

        /// <summary>
        /// Test LinkTokenCreate
        /// </summary>
        [Fact]
        public void LinkTokenCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EndUserDetailsRequest endUserDetailsRequest = null;
            //var response = instance.LinkTokenCreate(endUserDetailsRequest);
            //Assert.IsType<LinkToken>(response);
        }
    }
}
