/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Merge.HRISClient.Client;
using Merge.HRISClient.Api;
// uncomment below to import models
//using Merge.HRISClient.Model;

namespace Merge.HRISClient.Test.Api
{
    /// <summary>
    ///  Class for testing SelectiveSyncApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SelectiveSyncApiTests : IDisposable
    {
        private SelectiveSyncApi instance;

        public SelectiveSyncApiTests()
        {
            instance = new SelectiveSyncApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SelectiveSyncApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SelectiveSyncApi
            //Assert.IsType<SelectiveSyncApi>(instance);
        }

        /// <summary>
        /// Test SelectiveSyncConfigurationsList
        /// </summary>
        [Fact]
        public void SelectiveSyncConfigurationsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //var response = instance.SelectiveSyncConfigurationsList(xAccountToken);
            //Assert.IsType<List<LinkedAccountSelectiveSyncConfiguration>>(response);
        }

        /// <summary>
        /// Test SelectiveSyncConfigurationsUpdate
        /// </summary>
        [Fact]
        public void SelectiveSyncConfigurationsUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //LinkedAccountSelectiveSyncConfigurationListRequest linkedAccountSelectiveSyncConfigurationListRequest = null;
            //var response = instance.SelectiveSyncConfigurationsUpdate(xAccountToken, linkedAccountSelectiveSyncConfigurationListRequest);
            //Assert.IsType<List<LinkedAccountSelectiveSyncConfiguration>>(response);
        }

        /// <summary>
        /// Test SelectiveSyncMetaList
        /// </summary>
        [Fact]
        public void SelectiveSyncMetaListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //string commonModel = null;
            //string cursor = null;
            //int? pageSize = null;
            //var response = instance.SelectiveSyncMetaList(xAccountToken, commonModel, cursor, pageSize);
            //Assert.IsType<PaginatedConditionSchemaList>(response);
        }
    }
}
