/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// Defines AccountTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountTypeEnum
    {
        /// <summary>
        /// Enum SAVINGS for value: SAVINGS
        /// </summary>
        [EnumMember(Value = "SAVINGS")]
        SAVINGS = 1,

        /// <summary>
        /// Enum CHECKING for value: CHECKING
        /// </summary>
        [EnumMember(Value = "CHECKING")]
        CHECKING = 2

    }

}
