/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// Defines BenefitPlanTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BenefitPlanTypeEnum
    {
        /// <summary>
        /// Enum MEDICAL for value: MEDICAL
        /// </summary>
        [EnumMember(Value = "MEDICAL")]
        MEDICAL = 1,

        /// <summary>
        /// Enum DENTAL for value: DENTAL
        /// </summary>
        [EnumMember(Value = "DENTAL")]
        DENTAL = 2,

        /// <summary>
        /// Enum VISION for value: VISION
        /// </summary>
        [EnumMember(Value = "VISION")]
        VISION = 3,

        /// <summary>
        /// Enum HSA for value: HSA
        /// </summary>
        [EnumMember(Value = "HSA")]
        HSA = 4,

        /// <summary>
        /// Enum FSAMEDICAL for value: FSA_MEDICAL
        /// </summary>
        [EnumMember(Value = "FSA_MEDICAL")]
        FSAMEDICAL = 5,

        /// <summary>
        /// Enum FSADEPENDENTCARE for value: FSA_DEPENDENT_CARE
        /// </summary>
        [EnumMember(Value = "FSA_DEPENDENT_CARE")]
        FSADEPENDENTCARE = 6,

        /// <summary>
        /// Enum SIMPLEIRA for value: SIMPLE_IRA
        /// </summary>
        [EnumMember(Value = "SIMPLE_IRA")]
        SIMPLEIRA = 7,

        /// <summary>
        /// Enum _401K for value: _401K
        /// </summary>
        [EnumMember(Value = "_401K")]
        _401K = 8,

        /// <summary>
        /// Enum ROTH401K for value: ROTH_401K
        /// </summary>
        [EnumMember(Value = "ROTH_401K")]
        ROTH401K = 9,

        /// <summary>
        /// Enum OTHERNONTAXABLE for value: OTHER_NON_TAXABLE
        /// </summary>
        [EnumMember(Value = "OTHER_NON_TAXABLE")]
        OTHERNONTAXABLE = 10,

        /// <summary>
        /// Enum COMMUTERTRANSIT for value: COMMUTER_TRANSIT
        /// </summary>
        [EnumMember(Value = "COMMUTER_TRANSIT")]
        COMMUTERTRANSIT = 11,

        /// <summary>
        /// Enum COMMUTERPARKING for value: COMMUTER_PARKING
        /// </summary>
        [EnumMember(Value = "COMMUTER_PARKING")]
        COMMUTERPARKING = 12,

        /// <summary>
        /// Enum _401KLOANPAYMENT for value: _401K_LOAN_PAYMENT
        /// </summary>
        [EnumMember(Value = "_401K_LOAN_PAYMENT")]
        _401KLOANPAYMENT = 13,

        /// <summary>
        /// Enum SHORTDISABILITY for value: SHORT_DISABILITY
        /// </summary>
        [EnumMember(Value = "SHORT_DISABILITY")]
        SHORTDISABILITY = 14,

        /// <summary>
        /// Enum LONGDISABILITY for value: LONG_DISABILITY
        /// </summary>
        [EnumMember(Value = "LONG_DISABILITY")]
        LONGDISABILITY = 15,

        /// <summary>
        /// Enum LIFE for value: LIFE
        /// </summary>
        [EnumMember(Value = "LIFE")]
        LIFE = 16,

        /// <summary>
        /// Enum SEPIRA for value: SEP_IRA
        /// </summary>
        [EnumMember(Value = "SEP_IRA")]
        SEPIRA = 17,

        /// <summary>
        /// Enum SARSEP for value: SARSEP
        /// </summary>
        [EnumMember(Value = "SARSEP")]
        SARSEP = 18,

        /// <summary>
        /// Enum CUSTOMTAXABLE for value: CUSTOM_TAXABLE
        /// </summary>
        [EnumMember(Value = "CUSTOM_TAXABLE")]
        CUSTOMTAXABLE = 19,

        /// <summary>
        /// Enum _403B for value: _403B
        /// </summary>
        [EnumMember(Value = "_403B")]
        _403B = 20,

        /// <summary>
        /// Enum ROTH403B for value: ROTH_403B
        /// </summary>
        [EnumMember(Value = "ROTH_403B")]
        ROTH403B = 21,

        /// <summary>
        /// Enum STUDENTLOAN for value: STUDENT_LOAN
        /// </summary>
        [EnumMember(Value = "STUDENT_LOAN")]
        STUDENTLOAN = 22

    }

}
