/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// * &#x60;SALARY&#x60; - SALARY * &#x60;REIMBURSEMENT&#x60; - REIMBURSEMENT * &#x60;OVERTIME&#x60; - OVERTIME * &#x60;BONUS&#x60; - BONUS
    /// </summary>
    /// <value>* &#x60;SALARY&#x60; - SALARY * &#x60;REIMBURSEMENT&#x60; - REIMBURSEMENT * &#x60;OVERTIME&#x60; - OVERTIME * &#x60;BONUS&#x60; - BONUS</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EarningTypeEnum
    {
        /// <summary>
        /// Enum SALARY for value: SALARY
        /// </summary>
        [EnumMember(Value = "SALARY")]
        SALARY = 1,

        /// <summary>
        /// Enum REIMBURSEMENT for value: REIMBURSEMENT
        /// </summary>
        [EnumMember(Value = "REIMBURSEMENT")]
        REIMBURSEMENT = 2,

        /// <summary>
        /// Enum OVERTIME for value: OVERTIME
        /// </summary>
        [EnumMember(Value = "OVERTIME")]
        OVERTIME = 3,

        /// <summary>
        /// Enum BONUS for value: BONUS
        /// </summary>
        [EnumMember(Value = "BONUS")]
        BONUS = 4

    }

}
