/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// Defines FlsaStatusEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FlsaStatusEnum
    {
        /// <summary>
        /// Enum EXEMPT for value: EXEMPT
        /// </summary>
        [EnumMember(Value = "EXEMPT")]
        EXEMPT = 1,

        /// <summary>
        /// Enum SALARIEDNONEXEMPT for value: SALARIED_NONEXEMPT
        /// </summary>
        [EnumMember(Value = "SALARIED_NONEXEMPT")]
        SALARIEDNONEXEMPT = 2,

        /// <summary>
        /// Enum NONEXEMPT for value: NONEXEMPT
        /// </summary>
        [EnumMember(Value = "NONEXEMPT")]
        NONEXEMPT = 3,

        /// <summary>
        /// Enum OWNER for value: OWNER
        /// </summary>
        [EnumMember(Value = "OWNER")]
        OWNER = 4

    }

}
