/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// * &#x60;TEAM&#x60; - TEAM * &#x60;DEPARTMENT&#x60; - DEPARTMENT * &#x60;COST_CENTER&#x60; - COST_CENTER * &#x60;BUSINESS_UNIT&#x60; - BUSINESS_UNIT * &#x60;GROUP&#x60; - GROUP
    /// </summary>
    /// <value>* &#x60;TEAM&#x60; - TEAM * &#x60;DEPARTMENT&#x60; - DEPARTMENT * &#x60;COST_CENTER&#x60; - COST_CENTER * &#x60;BUSINESS_UNIT&#x60; - BUSINESS_UNIT * &#x60;GROUP&#x60; - GROUP</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GroupTypeEnum
    {
        /// <summary>
        /// Enum TEAM for value: TEAM
        /// </summary>
        [EnumMember(Value = "TEAM")]
        TEAM = 1,

        /// <summary>
        /// Enum DEPARTMENT for value: DEPARTMENT
        /// </summary>
        [EnumMember(Value = "DEPARTMENT")]
        DEPARTMENT = 2,

        /// <summary>
        /// Enum COSTCENTER for value: COST_CENTER
        /// </summary>
        [EnumMember(Value = "COST_CENTER")]
        COSTCENTER = 3,

        /// <summary>
        /// Enum BUSINESSUNIT for value: BUSINESS_UNIT
        /// </summary>
        [EnumMember(Value = "BUSINESS_UNIT")]
        BUSINESSUNIT = 4,

        /// <summary>
        /// Enum GROUP for value: GROUP
        /// </summary>
        [EnumMember(Value = "GROUP")]
        GROUP = 5

    }

}
