/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.HRISClient.Client.OpenAPIDateConverter;

namespace Merge.HRISClient.Model
{
    /// <summary>
    /// Defines MaritalStatusEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MaritalStatusEnum
    {
        /// <summary>
        /// Enum SINGLE for value: SINGLE
        /// </summary>
        [EnumMember(Value = "SINGLE")]
        SINGLE = 1,

        /// <summary>
        /// Enum MARRIEDFILINGJOINTLY for value: MARRIED_FILING_JOINTLY
        /// </summary>
        [EnumMember(Value = "MARRIED_FILING_JOINTLY")]
        MARRIEDFILINGJOINTLY = 2,

        /// <summary>
        /// Enum MARRIEDFILINGSEPARATELY for value: MARRIED_FILING_SEPARATELY
        /// </summary>
        [EnumMember(Value = "MARRIED_FILING_SEPARATELY")]
        MARRIEDFILINGSEPARATELY = 3,

        /// <summary>
        /// Enum HEADOFHOUSEHOLD for value: HEAD_OF_HOUSEHOLD
        /// </summary>
        [EnumMember(Value = "HEAD_OF_HOUSEHOLD")]
        HEADOFHOUSEHOLD = 4,

        /// <summary>
        /// Enum QUALIFYINGWIDOWORWIDOWERWITHDEPENDENTCHILD for value: QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD
        /// </summary>
        [EnumMember(Value = "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD")]
        QUALIFYINGWIDOWORWIDOWERWITHDEPENDENTCHILD = 5

    }

}
