name: NuGet Publish

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'
  NUGET_REPOSITORY_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dotnet SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build & package project
        run: |
          dotnet pack -c Release -o out

      - name: Push to GitHub package registry
        run: dotnet nuget push ./out/*.nupkg --source ${{ env.NUGET_REPOSITORY_URL }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols true
